In [141]:
import numpy as np
import pandas as pd

test = pd.read_csv("./TV_price_test.csv")
train = pd.read_csv("./TV_price_train.csv")

display(test)
display(train)

ID  화면크기  형태   해상도  화면비율  LCD  LED  OLED  QLED  단차  부가기능
0        11    55   0  2160     1    0    1     0     0   3     1
1        25    55   0  2160     1    0    1     0     0   3     1
2        31    55   0  2160     1    0    1     0     0   3     1
3        33    55   0  2160     1    0    1     0     0   3     1
4        44    65   0  2160     1    0    1     0     0   5     7
...     ...   ...  ..   ...   ...  ...  ...   ...   ...  ..   ...
2995  20637    49   0  1080     1    0    1     0     0   2     6
2996  20639    49   0  1080     1    0    1     0     0   2     6
2997  20642    49   0  1080     1    0    1     0     0   2     6
2998  20643    49   0  1080     1    0    1     0     0   2     6
2999  20664    49   0  1080     1    0    1     0     0   2     6

[3000 rows x 11 columns]

ID        판매가  화면크기  형태   해상도  화면비율  LCD  LED  OLED  QLED  단차  부가기능
0         8   396240.0    55   0  2160     1    0    1     0     0   3     1
1         9   412870.0    55   0  2160     1    0    1     0     0   3     1
2        10   414590.0    55   0  2160     1    0    1     0     0   3     1
3        14   418000.0    55   0  2160     1    0    1     0     0   3     1
4        15   419000.0    55   0  2160     1    0    1     0     0   3     1
...     ...        ...   ...  ..   ...   ...  ...  ...   ...   ...  ..   ...
6995  20670  1271670.0    49   0  1080     1    0    1     0     0   2     6
6996  20672  1441670.0    49   0  1080     1    0    1     0     0   2     6
6997  20673  1441680.0    49   0  1080     1    0    1     0     0   2     6
6998  20675  1571400.0    49   0  1080     1    0    1     0     0   2     6
6999  20676  2894380.0    49   0  1080     1    0    1     0     0   2     6

[7000 rows x 12 columns]

In [142]:
display(test.isnull().sum())
display(train.isnull().sum())

ID      0
화면크기    0
형태      0
해상도     0
화면비율    0
LCD     0
LED     0
OLED    0
QLED    0
단차      0
부가기능    0
dtype: int64

ID      0
판매가     0
화면크기    0
형태      0
해상도     0
화면비율    0
LCD     0
LED     0
OLED    0
QLED    0
단차      0
부가기능    0
dtype: int64

In [143]:
tv_id = train['ID']
drop_col = ["ID","판매가"]

In [144]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import train_test_split

In [145]:
train_input = train.drop(columns=drop_col)
test_input = test.drop(columns="ID")
train_target = train['판매가']

train_x, test_x, train_y, test_y = train_test_split(train_input, train_target, test_size = 0.3, random_state = 35)

In [146]:
lr = LinearRegression()
rf = RandomForestRegressor()
gr = GradientBoostingRegressor()

lr.fit(train_x, train_y)
rf.fit(train_x, train_y)
gr.fit(train_x, train_y)

GradientBoostingRegressor()

In [147]:
pred_lr = lr.predict(test_x)

pred_rf = rf.predict(test_x)

pred_gr = gr.predict(test_x)

In [148]:
display(pred_lr)
display(pred_rf)
display(pred_gr)

array([ 394785.34677485,  869741.36213499,  468954.46631794, ...,
        989838.10077143, 1471456.8245566 , 1609226.52553607])

array([ 651106.46713972,  567695.40869313,  880244.12340191, ...,
        683653.86319505, 1617069.99647658,  839457.87587029])

array([ 586956.25339749,  808146.76919286,  709626.49327154, ...,
        588411.13616009, 1519103.48547994,  999049.44366001])

In [149]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

In [150]:
def display_score (test_y, pred):
    mae = mean_absolute_error(test_y, pred)
    mse = mean_squared_error(test_y, pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(test_y, pred)
    print("MAE: {0:.4f} , MSE: {1:.4f} , RMSE: {2:.4f} , R2: {3:.4f}".format(mae,mse,rmse,r2))
    print(" ")

In [151]:
display_score(test_y, pred_lr)

display_score(test_y, pred_rf)

display_score(test_y, pred_gr)

MAE: 637796.2821 , MSE: 1134142378491.1943 , RMSE: 1064961.2099 , R2: 0.6062
 
MAE: 314200.7152 , MSE: 331069885103.1133 , RMSE: 575386.7266 , R2: 0.8851
 
MAE: 377087.4866 , MSE: 410033372537.2386 , RMSE: 640338.4828 , R2: 0.8576
 


In [155]:
result =  pd.DataFrame(
    {
        "ID":test['ID'],
        "predict":rf.predict(test_input)
    }
)

In [156]:
display(result)

ID       predict
0        11  4.305239e+05
1        25  4.305239e+05
2        31  4.305239e+05
3        33  4.305239e+05
4        44  1.914227e+06
...     ...           ...
2995  20637  1.083069e+06
2996  20639  1.083069e+06
2997  20642  1.083069e+06
2998  20643  1.083069e+06
2999  20664  1.083069e+06

[3000 rows x 2 columns]

In [153]:
result.to_csv('./2409_성의근_회귀.csv')

In [154]:
#MAE, MSE, RMSE가 가장 낮고 R2가 가장높은 랜덤포레스트회귀를 최종선택하였다